In [2]:
!nvidia-smi

Sat Feb  4 23:02:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    30W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
import torch
torch.cuda.is_available() # выясняем есть ли на машине GPU

True

In [7]:
torch.cuda.device_count()

1

In [ ]:
# чтобы отправить вычисления на девайс, 
# надо создать переменную с ним 
# число - номер видокарты в компе
torch.device('cuda:0')

In [ ]:
# такой девайс поможет вернуть вычисления на cpu
torch.device('cpu')

In [8]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [9]:
# на чипах M1 или M2 тоже можно считать 
# CUDA сделала поддержку, но я пока не тестил
# должно работать хуже полноценной видеокарты но лучше CPU 

In [10]:
x = torch.randn(10, 10).to(device)
x

tensor([[ 0.4940,  1.2682, -1.0555, -0.3774,  0.2309,  0.0751,  0.5501,  0.1471,
         -0.6900,  0.3678],
        [ 1.2831, -1.1831,  0.5866,  0.5913,  0.5013, -1.2075,  1.6582,  0.2835,
         -0.5538, -1.7885],
        [ 1.2968, -0.6125,  1.4125,  0.7875, -0.9539,  0.2162, -0.5699,  1.7864,
         -0.3212, -0.6004],
        [-0.1368,  0.3665,  0.5276,  0.3405, -0.8513,  1.4315,  0.8328, -1.2415,
         -0.3661, -0.9161],
        [ 1.1563, -0.0644, -1.1057, -0.9068, -1.1521,  0.8087,  0.5202, -0.9158,
          0.1796,  0.0395],
        [ 1.4475, -0.7495, -1.8361, -2.3526,  0.8406, -1.0360,  0.9676, -0.8947,
         -1.6046, -1.7287],
        [ 1.1179, -0.7721, -0.0830, -0.3833,  1.3195,  1.6918,  2.0732, -0.3755,
         -0.3628, -0.8152],
        [-0.4569,  0.7572, -1.5697,  0.4656,  0.9502,  0.9881, -0.6074, -0.2223,
         -0.5957,  0.6357],
        [-1.1210,  0.8653, -0.6431, -1.2508,  1.3576, -1.1747, -0.8135,  0.6152,
         -0.4770,  1.0068],
        [ 0.1855, -

In [12]:
!echo $CUDA_VISIBLE_DEVICES

In [13]:
x = torch.randn(10, 10, device=device)
x

tensor([[-0.2305,  1.7533, -0.7878,  1.2625,  0.1171, -0.7931, -0.8220,  1.5732,
         -1.0936,  1.5053],
        [ 1.7312,  1.0739,  0.2143, -1.1676,  1.2849,  0.1820, -0.9924,  1.2137,
         -0.7039, -0.2748],
        [ 0.4329,  0.9440, -0.4459,  1.5553,  0.9329,  0.6878,  0.0446, -0.0293,
         -0.7106,  0.5674],
        [ 1.6844,  1.3877, -0.3441,  1.0064, -1.6527, -0.2623,  0.2892, -0.7749,
          0.8195,  0.9864],
        [-0.8415,  0.0537,  1.2344, -0.5327,  0.9992, -0.3230, -1.6167,  0.0243,
         -2.1348,  0.1886],
        [ 1.0107,  0.5081, -1.4460, -1.9167, -0.2820,  0.6500,  0.0458,  0.2480,
          0.8121,  0.0285],
        [-0.3316,  0.9338, -0.6264,  0.5101, -0.4083,  0.7145, -1.3306,  0.8077,
         -1.3127,  1.8818],
        [-1.9281,  0.1223,  0.1739,  1.3887, -0.9529, -0.3363,  0.7615, -0.8214,
         -0.9968, -0.6844],
        [ 0.3799, -0.2678, -0.3567, -0.3760,  0.2535,  0.4894,  0.0494, -0.7052,
         -1.7848, -0.6254],
        [ 0.1549,  

In [14]:
x.cpu() # вернуть назад

tensor([[-0.2305,  1.7533, -0.7878,  1.2625,  0.1171, -0.7931, -0.8220,  1.5732,
         -1.0936,  1.5053],
        [ 1.7312,  1.0739,  0.2143, -1.1676,  1.2849,  0.1820, -0.9924,  1.2137,
         -0.7039, -0.2748],
        [ 0.4329,  0.9440, -0.4459,  1.5553,  0.9329,  0.6878,  0.0446, -0.0293,
         -0.7106,  0.5674],
        [ 1.6844,  1.3877, -0.3441,  1.0064, -1.6527, -0.2623,  0.2892, -0.7749,
          0.8195,  0.9864],
        [-0.8415,  0.0537,  1.2344, -0.5327,  0.9992, -0.3230, -1.6167,  0.0243,
         -2.1348,  0.1886],
        [ 1.0107,  0.5081, -1.4460, -1.9167, -0.2820,  0.6500,  0.0458,  0.2480,
          0.8121,  0.0285],
        [-0.3316,  0.9338, -0.6264,  0.5101, -0.4083,  0.7145, -1.3306,  0.8077,
         -1.3127,  1.8818],
        [-1.9281,  0.1223,  0.1739,  1.3887, -0.9529, -0.3363,  0.7615, -0.8214,
         -0.9968, -0.6844],
        [ 0.3799, -0.2678, -0.3567, -0.3760,  0.2535,  0.4894,  0.0494, -0.7052,
         -1.7848, -0.6254],
        [ 0.1549,  

In [ ]:
# Какая философия у работы с CUDA 
#
# картинки - надо предобработать (обычно на CPU)
# сформированный батчи передают на CUDA
# сама нейронка и поиск градиентов живут на GPU
#
# на GPU делаются все сложные операции 
# вся подготовка данных (логирование, метрики)
# должны происходить на CPU чтобы GPU не мешать 
#
# позже научимся смотреть на всякие продвинутые логгеры
# чтобы понимать как загружена CPU а как GPU


In [27]:
a = torch.rand([10**4,10**4])

In [28]:
a_python = a.tolist()

In [29]:
%%time
sum([a_python[i][j] for i in range(10**4) for j in range(10**4)])

CPU times: user 10.2 s, sys: 1.01 s, total: 11.2 s
Wall time: 11.2 s


50003634.091688156

In [30]:
a_numpy = a.numpy()

In [31]:
%%timeit
a_numpy.sum()

44.3 ms ± 989 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
%%timeit
a.sum()

36.2 ms ± 316 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
a_gpu = a.to(device)

In [35]:
%%timeit
a_gpu.sum()

1.45 ms ± 81.7 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# На малых размерах матрицы ускорения не будет. Нечего паралелить и мы будем убивать на отправку на GPU лишнее время. 

In [36]:
x = torch.rand(5, 5, requires_grad=True)
y = torch.rand(5, 5, requires_grad=False)

In [37]:
l = (x * y).sum()

In [38]:
l.backward()

In [39]:
x.grad

tensor([[0.2651, 0.3254, 0.5333, 0.5041, 0.6418],
        [0.5235, 0.6928, 0.1576, 0.2332, 0.9100],
        [0.4154, 0.7636, 0.5327, 0.7320, 0.9756],
        [0.2552, 0.2882, 0.9797, 0.0821, 0.6455],
        [0.8962, 0.6800, 0.3154, 0.7787, 0.6608]])

In [40]:
y.grad # нет градиента - логично :) 

In [41]:
# градиенты тащиться не будут,  
# вычислительного графа у нас не будет 
with torch.no_grad():
    l = (x * y).sum()
    l.backward()

RuntimeError: ignored

In [43]:
# более жесткая оптимизация вычислений
# в новых версиях торча оптимизирует
# ещё какие-то штуки дополнительно 
# в отличие от no_grad
# в каких-то сложных случаях 
# утверждается что она работает быстрее

with torch.inference_mode():
    l = (x * y).sum()
    # l.backward()