In [3]:
import torch
import numpy as np

In [5]:
x = torch.tensor([1, 2, 3, 4])
x

tensor([1, 2, 3, 4])

In [4]:
y = np.array([1, 2, 3, 4])
y

array([1, 2, 3, 4])

In [6]:
y.sum()

10

In [7]:
x.sum()

tensor(10)

In [8]:
X = torch.ones([4, 4])
X

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
Y = torch.randn([4,4])
Y

tensor([[ 1.1329,  1.2880,  0.0742,  0.3464],
        [ 0.7381, -0.4729,  1.3090,  0.7397],
        [ 0.2541, -1.3411,  0.4421,  0.7121],
        [-0.8222, -0.0226,  1.3181, -0.6330]])

In [10]:
Y + X

tensor([[ 2.1329,  2.2880,  1.0742,  1.3464],
        [ 1.7381,  0.5271,  2.3090,  1.7397],
        [ 1.2541, -0.3411,  1.4421,  1.7121],
        [ 0.1778,  0.9774,  2.3181,  0.3670]])

In [11]:
Y @ X

tensor([[ 2.8416,  2.8416,  2.8416,  2.8416],
        [ 2.3140,  2.3140,  2.3140,  2.3140],
        [ 0.0672,  0.0672,  0.0672,  0.0672],
        [-0.1596, -0.1596, -0.1596, -0.1596]])

In [13]:
Y

tensor([[ 1.1329,  1.2880,  0.0742,  0.3464],
        [ 0.7381, -0.4729,  1.3090,  0.7397],
        [ 0.2541, -1.3411,  0.4421,  0.7121],
        [-0.8222, -0.0226,  1.3181, -0.6330]])

In [14]:
X.double()

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [15]:
X.int()

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [17]:
X.long()

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [20]:
Y[Y > 0]

tensor([1.1329, 1.2880, 0.0742, 0.3464, 0.7381, 1.3090, 0.7397, 0.2541, 0.4421,
        0.7121, 1.3181])

In [23]:
Z = torch.empty([4,4])
Z

tensor([[-8.7701e+26,  4.5804e-41,  3.4402e-34,  0.0000e+00],
        [ 2.6078e-42,  0.0000e+00,  3.4404e-34,  0.0000e+00],
        [ 3.2304e-14,  4.5804e-41,  3.4404e-34,  0.0000e+00],
        [ 3.2304e-14,  4.5804e-41,  3.2304e-14,  4.5804e-41]])

In [28]:
b = torch.add(X, Y)
b

tensor([[ 2.1329,  2.2880,  1.0742,  1.3464],
        [ 1.7381,  0.5271,  2.3090,  1.7397],
        [ 1.2541, -0.3411,  1.4421,  1.7121],
        [ 0.1778,  0.9774,  2.3181,  0.3670]])

In [29]:
a = X + Y
a

tensor([[ 2.1329,  2.2880,  1.0742,  1.3464],
        [ 1.7381,  0.5271,  2.3090,  1.7397],
        [ 1.2541, -0.3411,  1.4421,  1.7121],
        [ 0.1778,  0.9774,  2.3181,  0.3670]])

In [27]:
torch.add(X, Y, out=Z)
Z

tensor([[ 2.1329,  2.2880,  1.0742,  1.3464],
        [ 1.7381,  0.5271,  2.3090,  1.7397],
        [ 1.2541, -0.3411,  1.4421,  1.7121],
        [ 0.1778,  0.9774,  2.3181,  0.3670]])

In [33]:
torch.all(a == Z)

tensor(True)

In [34]:
Z.numpy()

array([[ 2.132864  ,  2.2880476 ,  1.0742484 ,  1.3464184 ],
       [ 1.7381434 ,  0.52714074,  2.3090196 ,  1.7396767 ],
       [ 1.2541475 , -0.34106994,  1.4420888 ,  1.7120732 ],
       [ 0.17783648,  0.9773832 ,  2.3181362 ,  0.3670237 ]],
      dtype=float32)

### Задание 1: 

- При помощи numpy посчитайте сумму квадратов чисел от 1 до 10000
- Сделайте то же самое с помощью pytorch

In [35]:
a_list = list(range(1, 10**4))
a_list[:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
%time sum([i**2 for i in a_list])

CPU times: user 4.45 ms, sys: 960 µs, total: 5.41 ms
Wall time: 5.43 ms


333283335000

In [36]:
a_numpy = np.array(a_list)
a_numpy

array([   1,    2,    3, ..., 9997, 9998, 9999])

In [45]:
%timeit (a_numpy ** 2).sum()

17.1 µs ± 1.55 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
a_torch = torch.tensor(a_list)
a_torch

tensor([   1,    2,    3,  ..., 9997, 9998, 9999])

In [46]:
%timeit (a_torch ** 2).sum()

35.5 µs ± 5.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Градиенты

In [48]:
x = torch.randn([4,4], requires_grad=True)
y = torch.randn([4,4], requires_grad=True)

In [58]:
2*(x[0,0] + y[0, 0])

tensor(0.3117, grad_fn=<MulBackward0>)

In [52]:
l = torch.sum((x + y)**2)

In [53]:
print(x.grad)

None


In [54]:
l.backward()

In [55]:
x.grad

tensor([[ 0.3117, -4.4449,  3.1818,  1.8697],
        [-1.3449,  3.6281, -3.5299,  2.6911],
        [-2.8118, -3.8161, -1.6966,  4.5034],
        [-2.8644,  1.4682, -1.7957,  1.7880]])

In [63]:
x = torch.randn(1, requires_grad=True)
y = torch.randn(1, requires_grad=True)
x, y

(tensor([-0.8842], requires_grad=True), tensor([2.2856], requires_grad=True))

In [64]:
z = (x + y)**2
z.backward() # dz/dx = 2( x + y)

In [65]:
x.grad

tensor([2.8028])

In [66]:
2*(x + y)

tensor([2.8028], grad_fn=<MulBackward0>)

In [68]:
z = (x + y)**2
z.backward()

In [69]:
x.grad # = 2.8028 + 2.8028

tensor([5.6056])

In [75]:
x.grad.zero_() # надо обнулять после каждой итерации

tensor([0.])

Видеоккарту

In [76]:
# CUDA - библиотека для работы с видеокартами

In [2]:
!nvidia-smi

Mon Feb  6 18:08:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    28W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
torch.cuda.device_count()

1

In [6]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [7]:
torch.device('cpu')

device(type='cpu')

In [8]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [9]:
x = torch.randn([4, 4])

In [10]:
x.to(device)

tensor([[ 1.2373,  0.4178,  0.5503,  0.2309],
        [ 0.8638,  1.7922, -0.8114, -1.2415],
        [-1.5253,  0.2216,  0.9437, -1.8076],
        [ 0.3244,  0.2263, -2.0242,  0.4610]], device='cuda:0')

In [11]:
x.cpu()

tensor([[ 1.2373,  0.4178,  0.5503,  0.2309],
        [ 0.8638,  1.7922, -0.8114, -1.2415],
        [-1.5253,  0.2216,  0.9437, -1.8076],
        [ 0.3244,  0.2263, -2.0242,  0.4610]])

In [16]:
a = torch.randn([10**4, 10**4])
b = torch.randn([10**4, 10**4])

In [17]:
a_gpu = torch.randn([10**4, 10**4], device=device)
b_gpu = torch.randn([10**4, 10**4], device=device)

In [18]:
%time a @ b

CPU times: user 15.3 s, sys: 231 ms, total: 15.5 s
Wall time: 15.8 s


tensor([[  -2.3686,  110.2282,  100.5473,  ..., -198.3453,   32.0382,
           82.0891],
        [ -31.2025, -109.6571,  -81.8620,  ...,   40.3212,  -66.5889,
           63.2910],
        [ -97.2310,  -45.2022,  -63.2762,  ...,   70.9402,  234.6315,
           42.7506],
        ...,
        [-147.7971, -142.1883,   -0.7873,  ...,  162.6020,  -29.5452,
           28.3518],
        [-190.5967,   -7.1610,  -20.4488,  ...,  109.2233,    8.7952,
          -78.4880],
        [ 131.6610,  -75.3033,    8.3475,  ...,  146.7670, -132.2320,
          136.2658]])

In [19]:
%time a_gpu @ b_gpu

CPU times: user 1.93 ms, sys: 0 ns, total: 1.93 ms
Wall time: 1.29 ms


tensor([[-156.3741,  217.0767,   11.0942,  ...,   76.8329,   24.2592,
         -221.4573],
        [ -99.7288,   54.2805,  -26.6725,  ..., -216.3590, -107.8679,
         -232.6554],
        [ -11.2709,   69.2187,   -0.2716,  ...,  -93.1171,  -76.0619,
           -0.7071],
        ...,
        [ -52.7737,    4.7435, -105.3228,  ..., -168.2017,   74.6151,
           -6.3196],
        [  37.3631,  223.1654,   96.7217,  ...,    3.2983,   56.9396,
          176.1027],
        [  90.3743,  180.3072,   67.5939,  ...,  -26.9176,   61.4673,
          149.0665]], device='cuda:0')

In [1]:
!echo $CUDA_VISIBLE_DEVICES

In [7]:
import torch
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x.clone()
y[2] = torch.ones(3)

In [8]:
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1]])

In [9]:
x 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])